sudo: required
services:
  - docker

before_install:
  - docker build -t dvontrec/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dvontrec/react-test npm run test:coverage

# builds each container from production dockerfiles
after_success:
  - docker build -t dvontrec/multi-client -f ./client
  - docker build -t dvontrec/multi-nginx -f ./nginx
  - docker build -t dvontrec/multi-server -f ./server
  - docker build -t dvontrec/multi-worker -f ./worker
  #  log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Takes images and push to docker hub
  - docker push dvontrec/multi-client
  - docker push dvontrec/multi-nginx
  - docker push dvontrec/multi-server
  - docker push dvontrec/multi-worker
